### ISSUE TITLE
When I use cssvars like `--red-1`, this package will treet `--red-1` as a keyword

### ISSUE THREAD

**Issue by cq360767996** [Qix-/color-string#63]
So what is the purpose of changing `var keyword = /(\D+)/;` to `var keyword = /(\w+)/;` in index.js line 55?
Is it a bug or a extra consideration?
Maybe `var keyword = /^(\w+)$/;` will be more suitable?
Looking forward to your reply, thanks.

**Comment by cq360767996** [comment]
The way to reproduce. 
 1.  Fork [my project](https://github.com/cq360767996/demo.git).
 2. `yarn install` and `yarn build`
 3. You will see the result css in the `dist/css` fold.
 
```css
// source code
#app {
  color: var(--red);
}
```

```css
// transform code
#app {
  color: var(red);
}
```
